# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prints:
    runs-on: ubuntu-latest
    
    steps:
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world! This is Yannick
      
    # Runs a single command using the runners shell
    - name: Run another one-line script
      run: echo Woop! This is Yannick
      
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: prints

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a set of commands using the runners shell
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: syannickperrenet/autobuild-test
        tags: latest
        path: app/
